export const maininventory = [
  {
    MedicineName: "Sofa",
    ID: 1,
    Quantity: 5,
    Expiry: "25",
  },
  {
    MedicineName: "Television",
    ID: 2,
    Quantity: 3,
    Expiry: "15",
  },
  {
    MedicineName: "Bed",
    ID: 3,
    Quantity: 4,
    Expiry: "15",
  },
  {
    MedicineName: "Toaster",
    ID: 4,
    Quantity: 2,
    Expiry: "18",
  },
  {
    MedicineName: "Coffee Makern",
    ID: 5,
    Quantity: 4,
    Expiry: "22",
  },
  {
    MedicineName: "T-Shirt",
    ID: 6,
    Quantity: 10,
    Expiry: "50",
  },
  {
    MedicineName: "Laptop",
    ID: 7,
    Quantity: 3,
    Expiry: "20",
  },
  {
    MedicineName: "Dining Table",
    ID: 8,
    Quantity: 3,
    Expiry: "12",
  },
  {
    MedicineName: "Refrigerator",
    ID: 9,
    Quantity: 2,
    Expiry: "8",
  },
  {
    MedicineName: "Chair",
    ID: 10,
    Quantity: 1,
    Expiry: "30",
  },
  {
    MedicineName: "Blender",
    ID: 11,
    Quantity: 6,
    Expiry: "14",
  },
  {
    MedicineName: "Jeans",
    ID: 12,
    Quantity: 4,
    Expiry: "40",
  },
  {
    MedicineName: "Smartphone",
    ID: 13,
    Quantity: 8,
    Expiry: "18",
  },
  {
    MedicineName: "Nightstand",
    ID: 14,
    Quantity: 5,
    Expiry: "10",
  },
  {
    MedicineName: "Microwave",
    ID: 15,
    Quantity: 3,
    Expiry: "12",
  },
  {
    MedicineName: "Shirt",
    ID: 16,
    Quantity: 2,
    Expiry: "60",
  },
  {
    MedicineName: "Tablet",
    ID: 17,
    Quantity: 12,
    Expiry: "10",
  },
  {
    MedicineName: "Desk Lamp",
    ID: 18,
    Quantity: 12,
    Expiry: "15",
  },
  {
    MedicineName: "Vacuum Cleaner",
    ID: 19,
    Quantity: 3,
    Expiry: "10",
  },
  {
    MedicineName: "Couch",
    ID: 20,
    Quantity: 1,
    Expiry: "10",
  },
  {
    MedicineName: "Sofa",
    ID: 21,
    Quantity: 4,
    Expiry: "20",
  },
  {
    MedicineName: "Television",
    ID: 22,
    Quantity: 6,
    Expiry: "20",
  },
  {
    MedicineName: "Bed",
    ID: 23,
    Quantity: 4,
    Expiry: "12",
  },
  {
    MedicineName: "Toaster",
    ID: 24,
    Quantity: 5,
    Expiry: "11",
  },
  {
    MedicineName: "Coffee Makern",
    ID: 25,
    Quantity: 3,
    Expiry: "15",
  },
  {
    MedicineName: "T-Shirt",
    ID: 26,
    Quantity: 5,
    Expiry: "17",
  },
  {
    MedicineName: "Laptop",
    ID: 27,
    Quantity: 8,
    Expiry: "20",
  },
  {
    MedicineName: "Dining Table",
    ID: 28,
    Quantity: 4,
    Expiry: "17",
  },
  {
    MedicineName: "Refrigerator",
    ID: 29,
    Quantity: 3,
    Expiry: "9",
  },
  {
    MedicineName: "Chair",
    ID: 30,
    Quantity: 1,
    Expiry: "10",
  },
  {
    MedicineName: "Blender",
    ID: 31,
    Quantity: 5,
    Expiry: "25",
  },
  {
    MedicineName: "Jeans",
    ID: 32,
    Quantity: 3,
    Expiry: "11",
  },
  {
    MedicineName: "Smartphone",
    ID: 33,
    Quantity: 6,
    Expiry: "34",
  },
  {
    MedicineName: "Nightstand",
    ID: 34,
    Quantity: 4,
    Expiry: "14",
  },
  {
    MedicineName: "Microwave",
    ID: 35,
    Quantity: 2,
    Expiry: "8",
  },
  {
    MedicineName: "Shirt",
    ID: 36,
    Quantity: 1,
    Expiry: "10",
  },
  {
    MedicineName: "Tablet",
    ID: 37,
    Quantity: 10,
    Expiry: "50",
  },
  {
    MedicineName: "Desk Lamp",
    ID: 38,
    Quantity: 3,
    Expiry: "8",
  },
  {
    MedicineName: "Vacuum Cleaner",
    ID: 39,
    Quantity: 2,
    Expiry: "12",
  },
  {
    MedicineName: "Couch",
    ID: 40,
    Quantity: 1,
    Expiry: "9",
  },
  {
  MedicineName: "Sofa",
    ID: 41,
    Quantity: 3,
    Expiry: "17",
  },
  {
    MedicineName: "Television",
    ID: 42,
    Quantity: 5,
    Expiry: "15",
  },
  {
    MedicineName: "Bed",
    ID: 43,
    Quantity: 3,
    Expiry: "9",
  },
  {
    MedicineName: "Toaster",
    ID: 44,
    Quantity: 4,
    Expiry: "8",
  },
  {
    MedicineName: "Coffee Makern",
    ID: 45,
    Quantity: 2,
    Expiry: "13",
  },
  {
    MedicineName: "T-Shirt",
    ID: 46,
    Quantity: 4,
    Expiry: "14",
  },
  {
    MedicineName: "Laptop",
    ID: 47,
    Quantity: 6,
    Expiry: "25",
  },
  {
    MedicineName: "Dining Table",
    ID: 48,
    Quantity: 5,
    Expiry: "12",
  },
  {
    MedicineName: "Refrigerator",
    ID: 49,
    Quantity: 3,
    Expiry: "7",
  },
  {
    MedicineName: "Chair",
    ID: 50,
    Quantity: 1,
    Expiry: "6",
  },
  {
    MedicineName: "Blender",
    ID: 51,
    Quantity: 4,
    Expiry: "20",
  },
  {
    MedicineName: "Jeans",
    ID: 52,
    Quantity: 2,
    Expiry: "9",
  },
  {
    MedicineName: "Smartphone",
    ID: 53,
    Quantity: 5,
    Expiry: "28",
  },
  {
    MedicineName: "Nightstand",
    ID: 54,
    Quantity: 3,
    Expiry: "10",
  },
  {
    MedicineName: "Microwave",
    ID: 55,
    Quantity: 1,
    Expiry: "7",
  },
  {
    MedicineName: "Shirt",
    ID: 56,
    Quantity: 1,
    Expiry: "9",
  },
  {
    MedicineName: "Tablet",
    ID: 57,
    Quantity: 8,
    Expiry: "40",
  },
  {
    MedicineName: "Desk Lamp",
    ID: 58,
    Quantity: 2,
    Expiry: "6",
  },
  {
    MedicineName: "Vacuum Cleaner",
    ID: 59,
    Quantity: 2,
    Expiry: "10",
  },
  {
    MedicineName: "Couch",
    ID: 60,
    Quantity: 1,
    Expiry: "8",
  },
  {
    MedicineName: "Sofa",
    ID: 61,
    Quantity: 2,
    Expiry: "15",
  },
  {
    MedicineName: "Television",
    ID: 62,
    Quantity: 6,
    Expiry: "10",
  },
  {
    MedicineName: "Bed",
    ID: 63,
    Quantity: 5,
    Expiry: "4",
  },
  {
    MedicineName: "Toaster",
    ID: 64,
    Quantity: 6,
    Expiry: "10",
  },
  {
    MedicineName: "Coffee Makern",
    ID: 65,
    Quantity: 4,
    Expiry: "11",
  },
  {
    MedicineName: "T-Shirt",
    ID: 66,
    Quantity: 6,
    Expiry: "11",
  },
  {
    MedicineName: "Laptop",
    ID: 67,
    Quantity: 9,
    Expiry: "27",
  },
  {
    MedicineName: "Dining Table",
    ID: 68,
    Quantity: 6,
    Expiry: "7",
  },
  {
    MedicineName: "Refrigerator",
    ID: 69,
    Quantity: 4,
    Expiry: "8",
  },
  {
    MedicineName: "Chair",
    ID: 70,
    Quantity: 1,
    Expiry: "5",
  },
  {
    MedicineName: "Blender",
    ID: 71,
    Quantity: 3,
    Expiry: "17",
  },
  {
    MedicineName: "Jeans",
    ID: 72,
    Quantity: 3,
    Expiry: "6",
  },
  {
    MedicineName: "Smartphone",
    ID: 73,
    Quantity: 4,
    Expiry: "24",
  },
  {
    MedicineName: "Nightstand",
    ID: 74,
    Quantity: 2,
    Expiry: "8",
  },
  {
    MedicineName: "Microwave",
    ID: 75,
    Quantity: 2,
    Expiry: "5",
  },
  {
    MedicineName: "Shirt",
    ID: 76,
    Quantity: 1,
    Expiry: "8",
  },
  {
    MedicineName: "Tablet",
    ID: 77,
    Quantity: 7,
    Expiry: "35",
  },
  {
    MedicineName: "Desk Lamp",
    ID: 78,
    Quantity: 3,
    Expiry: "5",
  },
  {
    MedicineName: "Vacuum Cleaner",
    ID: 79,
    Quantity: 1,
    Expiry: "9",
  },
  {
    MedicineName: "Couch",
    ID: 80,
    Quantity: 1,
    Expiry: "7",
  },
  {MedicineName: "Sofa",
    ID: 81,
    Quantity: 3,
    Expiry: "12",
  },
  {
    MedicineName: "Television",
    ID: 82,
    Quantity: 6,
    Expiry: "10",
  },
  {
    MedicineName: "Bed",
    ID: 83,
    Quantity: 4,
    Expiry: "6",
  },
  {
    MedicineName: "Toaster",
    ID: 84,
    Quantity: 5,
    Expiry: "7",
  },
  {
    MedicineName: "Coffee Makern",
    ID: 85,
    Quantity: 3,
    Expiry: "8",
  },
  {
    MedicineName: "T-Shirt",
    ID: 86,
    Quantity: 5,
    Expiry: "8",
  },
  {
    MedicineName: "Laptop",
    ID: 87,
    Quantity: 7,
    Expiry: "20",
  },
  {
    MedicineName: "Dining Table",
    ID: 88,
    Quantity: 7,
    Expiry: "0",
  },
  {
    MedicineName: "Refrigerator",
    ID: 89,
    Quantity: 2,
    Expiry: "1",
  },
  {
    MedicineName: "Chair",
    ID: 90,
    Quantity: 1,
    Expiry: "4",
  },
  {
    MedicineName: "Blender",
    ID: 91,
    Quantity: 5,
    Expiry: "12",
  },
  {
    MedicineName: "Jeans",
    ID: 92,
    Quantity: 2,
    Expiry: "4",
  },
  {
    MedicineName: "Smartphone",
    ID: 13,
    Quantity: 3,
    Expiry: "21",
  },
  {
    MedicineName: "Nightstand",
    ID: 94,
    Quantity: 1,
    Expiry: "7",
  },
  {
    MedicineName: "Microwave",
    ID: 95,
    Quantity: 2,
    Expiry: "3",
  },
  {
    MedicineName: "Shirt",
    ID: 96,
    Quantity: 1,
    Expiry: "7",
  },
  {
    MedicineName: "Tablet",
    ID: 97,
    Quantity: 6,
    Expiry: "29",
  },
  {
    MedicineName: "Desk Lamp",
    ID: 98,
    Quantity: 2,
    Expiry: "1",
  },
  {
    MedicineName: "Vacuum Cleaner",
    ID: 99,
    Quantity: 1,
    Expiry: "8",
  },
  {
    MedicineName: "Couch",
    ID: 100,
    Quantity: 1,
    Expiry: "6",
  },
  {
    MedicineName: "Sofa",
    ID: 101,
    Quantity: 2,
    Expiry: "10",
  },
  {
    MedicineName: "Television",
    ID: 102,
    Quantity: 4,
    Expiry: "6",
  },
  {
    MedicineName: "Bed",
    ID: 103,
    Quantity: 3,
    Expiry: "2",
  },
  {
    MedicineName: "Toaster",
    ID: 104,
    Quantity: 2,
    Expiry: "1",
  },
  {
    MedicineName: "Coffee Makern",
    ID: 105,
    Quantity: 2,
    Expiry: "8",
  },
  {
    MedicineName: "T-Shirt",
    ID: 106,
    Quantity: 3,
    Expiry: "7",
  },
  {
    MedicineName: "Laptop",
    ID: 107,
    Quantity: 4,
    Expiry: "20",
  },
  {
    MedicineName: "Dining Table",
    ID: 108,
    Quantity: 2,
    Expiry: "2",
  },
  {
    MedicineName: "Refrigerator",
    ID: 109,
    Quantity: 2,
    Expiry: "8",
  },
  {
    MedicineName: "Chair",
    ID: 110,
    Quantity: 1,
    Expiry: "3",
  },
  {
    MedicineName: "Blender",
    ID: 111,
    Quantity: 3,
    Expiry: "9",
  },
  {
    MedicineName: "Jeans",
    ID: 112,
    Quantity: 2,
    Expiry: "4",
  },
  {
    MedicineName: "Smartphone",
    ID: 113,
    Quantity: 3,
    Expiry: "16",
  },
  {
    MedicineName: "Nightstand",
    ID: 114,
    Quantity: 2,
    Expiry: "4",
  },
  {
    MedicineName: "Microwave",
    ID: 115,
    Quantity: 1,
    Expiry: "4",
  },
  {
    MedicineName: "Shirt",
    ID: 116,
    Quantity: 1,
    Expiry: "6",
  },
  {
    MedicineName: "Tablet",
    ID: 117,
    Quantity: 4,
    Expiry: "21",
  },
  {
    MedicineName: "Desk Lamp",
    ID: 118,
    Quantity: 1,
    Expiry: "3",
  },
  {
    MedicineName: "Vacuum Cleaner",
    ID: 119,
    Quantity: 1,
    Expiry: "6",
  },
  {
    MedicineName: "Couch",
    ID: 120,
    Quantity: 1,
    Expiry: "5",
  },

];
